# helm/polybot/values.yaml

replicaCount: 4

image:
  repository: lidorbashari/polybot
  tag: 2.2.5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8443

env:
  SQS_URL: https://sqs.eu-north-1.amazonaws.com/352708296901/lidor_k8s_queue_project
  TELEGRAM_APP_URL: https://lidor.devops-int-college.com
  AWS_DEFAULT_REGION: eu-north-1

awsSecretName: aws-credentials
