name: Build and Deploy Polybot

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: lidorbashari/polybot
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  INFRA_PAT: ${{ secrets.INFRA_PAT }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Polybot repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      id: build-image
      run: |
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Clone infra repo using PAT
      run: |
        git clone https://x-access-token:${{ env.INFRA_PAT }}@github.com/lidorbashari/NetflixInfra.git NetflixInfra

    - name: Update values.yaml with new image tag
      run: |
        sed -i "s|tag: .*|tag: \"$IMAGE_TAG\"|g" NetflixInfra/tf/polybot/values.yaml

    - name: Commit and push changes to infra repo
      run: |
        cd infra
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add tf/polybot/values.yaml
        git commit -m "Update polybot image tag to $IMAGE_TAG"
        git push
